/// Package-root export for `enclavia_dart`.
///
/// The generated UniFFI bindings live in `enclavia_ffi.dart` (generated by
/// UniFFI-Dart from `enclavia-ffi`, the same shared Rust interface crate the
/// Swift and Kotlin bindings are built from); this file provides the
/// conventional `package:enclavia_dart/enclavia_dart.dart` entrypoint
/// expected by pub.dev.
library;

export 'enclavia_ffi.dart';
